stages:
  - lint
  - build

pylint:
  stage: lint
  image: python:3.11
  before_script:
    - pip install pylint
  script: 
    - pylint **/*.py
  only:
    - main

sphinx:
  stage: build
  image: python:3.11
  before_script:
    - pip install sphinx
  script: 
    - sphinx-build -b html docs/ public/
  artifacts:
    paths:
      - public/
  only:
    - main

