base_url: "https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/"

urls:
  - "https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/annual/air_temperature_mean/regional_averages_tm_year.txt"
  - "https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/annual/precipitation/regional_averages_rr_year.txt"
  - "https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/annual/sunshine_duration/regional_averages_sd_year.txt"
  - "https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/annual/tropical_nights_tminGE20/regional_averages_tnes_year.txt"
  - "https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/annual/summer_days/regional_averages_txas_year.txt"
  - "https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/annual/precipGE20mm_days/regional_averages_rrsgs_year.txt"
  - "https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/annual/precipGE10mm_days/regional_averages_rrsfs_year.txt"
  - "https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/annual/ice_days/regional_averages_txcs_year.txt"
  - "https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/annual/hot_days/regional_averages_txbs_year.txt"
  - "https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/annual/frost_days/regional_averages_tnas_year.txt"
  - "https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/monthly/air_temperature_mean/regional_averages_tm_{}.txt"
  - "https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/monthly/precipitation/regional_averages_rr_{}.txt"
  - "https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/monthly/sunshine_duration/regional_averages_sd_{}.txt"

headers:
  -  "Jahr;Monat"
  -  "brandenburg/berlin"
  -  "brandenburg"
  -  "baden-wuerttemberg"
  -  "bayern"
  -  "hessen"
  -  "mecklenburg-vorpommern"
  -  "niedersachsen"
  -  "niedersachsen/hamburg/bremen"
  -  "nordrhein-westfalen"
  -  "rheinland-pfalz"
  -  "schleswig-holstein"
  -  "saarland"
  -  "sachsen"
  -  "sachsen-anhalt"
  -  "thueringen/sachsen-anhalt"
  -  "thueringen"
  -  "deutschland"

months:
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"

month_names:
  - "january"
  - "february"
  - "march"
  - "april"
  - "may"
  - "june"
  - "july"
  - "august"
  - "september"
  - "october"
  - "november" 
  - "december"

monthly_data_type:
  - "air_temperature_mean"
  - "precipitation"
  - "sunshine_duration"

interval:
  - "annual"
  - "monthly"
